// Generate the Unicode case tables the C runtime uses.
//
//   node tools/gen-unicase.mjs           write the header
//   node tools/gen-unicase.mjs --check   fail if what is committed differs
//
// `upper` and `lower` were the last two string methods the backend refused,
// and they were refused for a good reason: their answers come out of
// Unicode's case tables, and a C version that agreed for ASCII and diverged
// on anyone else's alphabet is exactly the mis-acceptance R23 forbids.
//
// So the tables are not written by hand and not transcribed from a data
// file. They are *asked of the interpreter*: for every code point, what
// does `toUpperCase` say? The result is a table that agrees with the other
// engine by construction rather than by inspection, which is the only kind
// of agreement worth having between two implementations of one language.
//
// That also means this file is the whole dependency. There is no
// UnicodeData.txt to download and no version to pin: the answer is whatever
// the Node that runs `npm test` believes, and CI regenerates and diffs so a
// Node upgrade that changed one mapping would be a red build rather than a
// quiet divergence.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "compiler",
  "src", "backend", "c", "runtime", "unicase.h");

const SURROGATE_LO = 0xd800;
const SURROGATE_HI = 0xdfff;

/** Every code point, minus the surrogates, which are not characters. */
function* points() {
  for (let cp = 0; cp < 0x110000; cp++) {
    if (cp >= SURROGATE_LO && cp <= SURROGATE_HI) continue;
    yield cp;
  }
}

/**
 * One-to-one mappings, collapsed into runs sharing a delta. Most of Unicode
 * cases in blocks -- a-z is one run, Cyrillic is another -- so 1,478
 * mappings become 688 runs.
 */
function caseRanges(which) {
  const out = [];
  let cur = null;
  for (const cp of points()) {
    const c = String.fromCodePoint(cp);
    const m = which === "upper" ? c.toUpperCase() : c.toLowerCase();
    if (m === c || [...m].length !== 1) { cur = null; continue; }
    const d = m.codePointAt(0) - cp;
    if (cur && cur.d === d && cur.hi + 1 === cp) { cur.hi = cp; continue; }
    cur = { lo: cp, hi: cp, d };
    out.push(cur);
  }
  return out;
}

/** The ones that map to more than one code point: ß to SS, and so on. */
function caseMulti(which) {
  const out = [];
  for (const cp of points()) {
    const c = String.fromCodePoint(cp);
    const m = which === "upper" ? c.toUpperCase() : c.toLowerCase();
    const to = [...m].map((x) => x.codePointAt(0));
    if (m === c || to.length < 2) continue;
    out.push({ from: cp, to });
  }
  return out;
}

/** A Unicode property, as runs. Used by the final-sigma rule below. */
function propertyRanges(re) {
  const out = [];
  let cur = null;
  for (const cp of points()) {
    if (!re.test(String.fromCodePoint(cp))) { cur = null; continue; }
    if (cur && cur.hi + 1 === cp) { cur.hi = cp; continue; }
    cur = { lo: cp, hi: cp };
    out.push(cur);
  }
  return out;
}

const hex = (n) => `0x${n.toString(16).padStart(4, "0")}`;

function rows(items, per, render) {
  const lines = [];
  for (let i = 0; i < items.length; i += per) {
    lines.push("  " + items.slice(i, i + per).map(render).join(" "));
  }
  return lines.join("\n");
}

function generate() {
  const upper = caseRanges("upper");
  const lower = caseRanges("lower");
  const upperMulti = caseMulti("upper");
  const lowerMulti = caseMulti("lower");
  const cased = propertyRanges(/\p{Cased}/u);
  const ignorable = propertyRanges(/\p{Case_Ignorable}/u);

  const maxTo = Math.max(...upperMulti.map((m) => m.to.length), ...lowerMulti.map((m) => m.to.length));

  return `/* Generated by tools/gen-unicase.mjs -- do not edit.
 *
 * Every entry was asked of the same JavaScript the interpreter runs on, so
 * the two engines agree on case mapping by construction rather than by
 * inspection. CI regenerates this and fails if it differs, which makes a
 * Node upgrade that changed one mapping a red build instead of a quiet
 * divergence between \`halka run\` and \`halka build\`.
 *
 * ${upper.length} upper runs, ${lower.length} lower runs, ${upperMulti.length} one-to-many upper,
 * ${lowerMulti.length} one-to-many lower, ${cased.length} Cased runs, ${ignorable.length} Case_Ignorable runs.
 */

#ifndef HALKA_UNICASE_H
#define HALKA_UNICASE_H

typedef struct { hk_char lo, hi; int32_t d; } hk_case_run;
typedef struct { hk_char lo, hi; } hk_char_run;
typedef struct { hk_char from; hk_char to[${maxTo}]; int n; } hk_case_multi;

/* One-to-one mappings, as runs sharing a delta. */
static const hk_case_run HK_UPPER_RUNS[] = {
${rows(upper, 4, (r) => `{ ${hex(r.lo)}, ${hex(r.hi)}, ${r.d} },`)}
};

static const hk_case_run HK_LOWER_RUNS[] = {
${rows(lower, 4, (r) => `{ ${hex(r.lo)}, ${hex(r.hi)}, ${r.d} },`)}
};

/* The ones that grow: German sharp s uppercases to two letters, and the
 * ligatures to two or three. */
static const hk_case_multi HK_UPPER_MULTI[] = {
${upperMulti.map((m) => `  { ${hex(m.from)}, { ${m.to.map(hex).join(", ")} }, ${m.to.length} },`).join("\n")}
};

static const hk_case_multi HK_LOWER_MULTI[] = {
${lowerMulti.map((m) => `  { ${hex(m.from)}, { ${m.to.map(hex).join(", ")} }, ${m.to.length} },`).join("\n")}
};

/* Needed only by the final-sigma rule: a capital sigma lowercases to the
 * final form when it ends a word, and to the ordinary one otherwise. */
static const hk_char_run HK_CASED[] = {
${rows(cased, 6, (r) => `{ ${hex(r.lo)}, ${hex(r.hi)} },`)}
};

static const hk_char_run HK_CASE_IGNORABLE[] = {
${rows(ignorable, 6, (r) => `{ ${hex(r.lo)}, ${hex(r.hi)} },`)}
};

#define HK_UPPER_RUNS_N ${upper.length}
#define HK_LOWER_RUNS_N ${lower.length}
#define HK_UPPER_MULTI_N ${upperMulti.length}
#define HK_LOWER_MULTI_N ${lowerMulti.length}
#define HK_CASED_N ${cased.length}
#define HK_CASE_IGNORABLE_N ${ignorable.length}

#endif /* HALKA_UNICASE_H */
`;
}

const text = generate();
if (process.argv.includes("--check")) {
  const have = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (have === text) {
    process.stdout.write(`unicase.h matches what this Node generates (${process.version})\n`);
  } else {
    process.stdout.write("::error::unicase.h does not match tools/gen-unicase.mjs. Run it and commit the result.\n");
    process.stderr.write(`unicase.h is stale under ${process.version}. Run: node tools/gen-unicase.mjs\n`);
    process.exit(1);
  }
} else {
  writeFileSync(OUT, text);
  process.stdout.write(`wrote ${OUT} (${(text.length / 1024).toFixed(1)} KiB, Node ${process.version})\n`);
}
